In [1]:
import numpy as np

# Original array
x = np.array([10.0, 15.0, 8.0, 12.0, 20.0])

# Calculate mean and standard deviation
mean = np.mean(x)
std_dev = np.std(x) # Note: np.std calculates population std dev by default

# Add a small epsilon for numerical stability (important in neural nets!)
epsilon = 1e-5
std_dev_stable = np.sqrt(np.var(x) + epsilon) # Or simply std_dev + epsilon if std_dev isn't zero

# Normalize
x_normalized = (x - mean) / std_dev_stable # Using std_dev_stable is closer to LayerNorm

print("Original array:", x)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("---")
print("Normalized array:", x_normalized)
print("Mean of normalized:", np.mean(x_normalized))
print("Variance of normalized:", np.var(x_normalized))
print("Std Dev of normalized:", np.std(x_normalized))


Original array: [10. 15.  8. 12. 20.]
Mean: 13.0
Standard Deviation: 4.1952353926806065
---
Normalized array: [-0.71509674  0.47673116 -1.1918279  -0.23836558  1.66855906]
Mean of normalized: 0.0
Variance of normalized: 0.9999994318185044
Std Dev of normalized: 0.9999997159092119


In [16]:
import torch

# Create a simple tensor with known values
x = torch.tensor([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]])  # shape: (1, 2, 4)

print("Original shape:", x.shape)
print(x)

# First approach: view then transpose
# View to (1, 2, 2, 2) then transpose dimensions 1 and 2
v1 = x.view(1,2,3,2)
print("\nAfter view to (1, 2, 3, 2):")
print(v1)
t1 = v1.transpose(1, 2)
print("\nAfter transpose(1, 2):")
print(t1.shape)
print(t1)

# Second approach: try to view directly to final shape
# This will fail because tensors are stored in row-major order
try:
    v2 = x.view(1, 2, 2, 2).transpose(1, 2)
    direct_view = x.reshape(1, 2, 2, 2)  # This will have different values than v2
    print("\nDirect reshape gives different values:")
    print(direct_view)
    print("\nCompare with correct result:")
    print(v2)
except Exception as e:
    print("\nError:", e)

Original shape: torch.Size([1, 3, 4])
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

After view to (1, 2, 3, 2):
tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])

After transpose(1, 2):
torch.Size([1, 3, 2, 2])
tensor([[[[ 1,  2],
          [ 7,  8]],

         [[ 3,  4],
          [ 9, 10]],

         [[ 5,  6],
          [11, 12]]]])

Error: shape '[1, 2, 2, 2]' is invalid for input of size 12
